name: ci

on:
  push: { branches: [main] }
  pull_request:

jobs:
  ci:
    uses: schryer/pubkit/.github/workflows/rust-ci.yml@v{version}

  release:
    needs: ci
    uses: schryer/pubrel/.github/workflows/release.yml@v0.1.0
    with: { pub-version: v0.1.1, pubrel-version: v0.1.0 }
    permissions:
      contents: write
